baseurl = "http://localhost:1313/"
languagecode = "en-us"
pluralizelisttitles = false
title = "Adventure Time!!"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Episodes"
url = "/episodes"
weight = 2
[params]
banner = "/assets/images/about.jpg"
description = "Adventure Time is an American animated television series created by Pendleton Ward for Cartoon Network. The series follows the adventures of Finn, a human boy, and his best friend and adoptive brother Jake, a dog with magical powers to change shape and grow and shrink at will. Finn and Jake live in the post-apocalyptic Land of Ooo. Along the way, they interact with the other main characters of the show: Princess Bubblegum, The Ice King, and Marceline the Vampire Queen."
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
